import React from "react";
import Head from "next/head";
import Hero from "../components/Hero/Hero";
import Subscribe from "../components/Subscribe/Subscribe";
import Featurettes from "../components/Featurettes";
const about = () => {
  return (
    <>
      <Head>
        <title>Mekoyo Production</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <div className="px-4 py-5  text-center row ">
          <h1 className="display-3 fw-bold">About Me</h1>
        </div>
      </Hero>
      <br />
      <br />
      <section className="container mt-5 pt-5">
        <div className="row">
          <div className="col-12">
            <h1 className="display-3 fw-bold">Biography</h1>
            <hr />
          </div>
          <div className="col-12">
            <p>
              Nnaemeka Ugochukwu Onusiriuka also known as Mr MEKOYO is a
              Versatile Nigerian musician, producer, songwriter and a
              Multi-Talented Intrumentalist. He worked as an assistant Engineer
              in C Mountain Studio Abuja, he also worked as a Chief Engineer in
              Keruzzo Studio Enugu.He set up his own recording facility in 2007.
              He is CEO/ Head of Productions of D Mekoyo Entertainment. Mr
              Mekoyo is presently heading the sound department of Dunamis
              international churches.
            </p>
            <p>
              He was responsible for Styl-plus highly acclaimed Single and has
              been mentioned on many artists&apos; sleeve credits as producer
              and writer. Mr Mekoyo Studied Mechanical Engineering in University
              of Nigeria Nsukka, but later branched into music full-time to
              fulfill a lifelong desire. His style comprises a wide spectrum of
              genres based on his careful understudy of such classical,hip-pop
              and traditional music He has won awards as a Music Producer as
              well as his other fields of interest. Mr Mekoyo released his much
              awaited first official single titled ‘Time to Shine’’ in 2002. The
              Song immediately became the NO.1 on most radio charts Nigeria.
              Today, he is known for producing some of the finest artistes in
              Nigeria. Noteworthy among these artistes is the Nigerian
              soul-singing sensation,STYL-PLUS, VECTOR, KEFEE, PAUL PLAY, TONY
              ONE WEEK, WEIRD MC, ELIJAH OYELADE, SOLOMON LANGE, PROSPER
              OCHIMANA, ASU EKIYE, and to mention a few. HE co-wrote the hit
              song ‘’KOKOROKO’’ by KEFEE.
            </p>
            <p>
              He is also responsible for the productions of Dr Pastor Paul
              enenche and Dr pastor Becky enenche of Dunamis. He is currently
              the head of sound in Dunamis international churches. Mr Mekoyo has
              won multiple awards for his creative and entrepreneurial
              contributions to the Nigerian music industry. Mr Mekoyo shot to
              limelight when he produced the popular hit single ‘’OLUFUNMI’’ by
              STYL-PLUS.
            </p>
            <p> Mr Mekoyo is happily married with four lovely children.</p>
          </div>
        </div>

        <div className="row my-5">
          <div className="col-12">
            <h1 className="display-3 fw-bold"> Why I&apos;m are here</h1>
            <hr />
          </div>
          <div className="col-12">
            <p>
              Mr Mekoyo has been known for an unparalleled commitment to
              customer satisfaction. It’s this standard of excellence that has
              provided the impetus for us to grow into the business we are
              today. For more information about the products and services we
              provide, reach out today.
            </p>
          </div>
        </div>

        <Featurettes />
        <Subscribe />
      </section>
    </>
  );
};

export default about;
