import React from "react";
import Head from "next/head";
import Hero from "../components/Hero/Hero";
import Subscribe from "../components/Subscribe/Subscribe";
const about = () => {
  return (
    <>
      <Head>
        <title>Mekoyo Production</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <div className="px-4 py-5  text-center row ">
          <h1 className="display-3 fw-bold">About Me</h1>
          <div className="row">
            <div className="col-10 mx-auto">
              <h4>My Mission is to impact Through Music</h4>
              <button className="btn btn-primary btn-sm rounded-0 p-3 mt-2">
                READ MORE
              </button>
            </div>
          </div>
        </div>
      </Hero>
      <br />
      <br />
      <section className="container mt-5 pt-5">
        <div className="row">
          <div className="col-12">
            <h1 className="display-3 fw-bold">Biography</h1>
            <hr />
          </div>
          <div className="col-12">
            <p>
              My name is Odunayo Yusuf, founder of O.Y Productions, i’m a
              prolific Music Producer, Sound Engineer and a Music Instructor. My
              productions cross a wide range of Afrobeat music styles,
              Dancehall, Afroswing, Afro-house, Afropop, Zouk, Afrotrap, Zouk
              and Reggae. With a constantly evolving sound, i enjoy
              experimenting with sounds which cross over into various musical
              genres. I’m also versatile music composer, song-writer and an
              aspiring speaker. I’m currently tutoring a diverse set of people
              through my music empowerment program. Having worked with major
              A-list artistes such as Olamide, Awilo logonba, Kida Kudz,
              Patoranking, Ice Prince, Stonebwoy, Wande Coal, Iyanya, amongst
              others and with a wealth of over 15 years’ experience learning and
              perfecting his craft. I’ve has progressively maintained the
              ability to connect to people, hence why they continue to expand
              and become more diverse as his career continues to grow. I’ve
              gained the support of industry tastemakers around the globe, and
              my production works have climbed the top charts numerous times.
              Having made my mark in the Afrobeat music world.
            </p>
          </div>
        </div>

        <div className="row my-5">
          <div className="col-12">
            <h1 className="display-3 fw-bold"> Why i'm are here</h1>
            <hr />
          </div>
          <div className="col-12">
            <p>
              Creativity lies in the mind of the one who is willing to solve
              problems with different strategies. OY Production, an amazing
              brand in the industry, has helped people particularly artists in
              achieving their goals. In short, his impact has and is still
              turning lives around for good. It is also known that no matter how
              good or successful a brand is, there is still always room for
              improvement.
            </p>
          </div>
        </div>

        {/* Featurettes  */}
        <div className="row featurette my-5 py-5 align-items-center ">
          <div className="col-md-7">
            <h2 className="featurette-heading">
              First featurette heading.{" "}
              <span className="text-sharp-gold">It’ll blow your mind.</span>
            </h2>
            <p className="lead">
              Some great placeholder content for the first featurette here.
              Imagine some exciting prose here.
            </p>
          </div>
          <div className="col-md-5">
            <img
              src="https://images.unsplash.com/photo-1463453091185-61582044d556?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YmxhY2slMjBtYW4lMjBwb3RyYWl0fGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60"
              className="img-fluid"
            />
          </div>
        </div>

        <div className="row featurette my-5 py-5 align-items-center">
          <div className="col-md-7 order-md-2">
            <h2 className="featurette-heading">
              Oh yeah, it’s that good.{" "}
              <span className="text-sharp-gold">See for yourself.</span>
            </h2>
            <p className="lead">
              Another featurette? Of course. More placeholder content here to
              give you an idea of how this layout would work with some actual
              real-world content in place.
            </p>
          </div>
          <div className="col-md-5 order-md-1">
            <img
              src="https://images.unsplash.com/photo-1528109688329-6a043167789d?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTl8fGJsYWNrJTIwbWFuJTIwcG90cmFpdHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60"
              className="img-fluid"
            />
          </div>
        </div>

        <div className="row featurette my-4 align-items-center">
          <div className="col-md-7">
            <h2 className="featurette-heading">
              And lastly, this one.{" "}
              <span className="text-sharp-gold">Checkmate.</span>
            </h2>
            <p className="lead">
              And yes, this is the last block of representative placeholder
              content. Again, not really intended to be actually read, simply
              here to give you a better view of what this would look like with
              some actual content. Your content.
            </p>
          </div>
          <div className="col-md-5">
            <img
              src="https://images.unsplash.com/photo-1509305717900-84f40e786d82?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmxhY2slMjBtYW4lMjBwb3RyYWl0fGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=900&q=60"
              className="img-fluid"
            />
          </div>
        </div>
        <Subscribe />
      </section>
    </>
  );
};

export default about;
