import Head from "next/head";
import CallToAction from "../components/CallToAction";
import VideoCard from "../components/Cards/VideoCard";
import FAQ from "../components/FAQ";
import Featurettes from "../components/Featurettes";
import Hero from "../components/Hero/Hero";
import Subscribe from "../components/Subscribe/Subscribe";
import ScrollAnimation from "react-animate-on-scroll";
export default function Home(props) {
  const videoIDs = [
    { id: "1kx0FfSexQ0" },
    { id: "5EfMInocDs8" },
    { id: "X3DDFB0BiQw" },
    { id: "Y6AKl_8XKJQ" },
  ];
  return (
    <div className="">
      <Head>
        <title>Mekoyo Production</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <div className="px-4 py-5 my-5 text-center">
          <img
            className="d-block mx-auto mb-4"
            src="https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2070&q=80"
            alt=""
            width="72"
            height="57"
          />
          <h1 className="display-5 fw-bold">Centered hero</h1>
          <div className="col-lg-6 mx-auto">
            <p className="lead mb-4">
              Quickly design and customize responsive mobile-first sites with
              Bootstrap, the world’s most popular front-end open source toolkit,
              featuring Sass variables and mixins, responsive grid system,
              extensive prebuilt components, and powerful JavaScript plugins.
            </p>
            <div className="d-grid gap-2 d-sm-flex justify-content-sm-center">
              <button
                type="button"
                className="btn btn-primary rounded-0 py-3 text-white  btn-lg px-4"
              >
                Get Started
              </button>
            </div>
          </div>
        </div>
      </Hero>
      <main className="container">
        <section className="py-5  text-center container">
          <div className="row py-lg-5">
            <div className="col-lg-6 col-md-8 mx-auto">
              <h1 className="fw-light text-sharp-gold">Album example</h1>
              <p className="lead text-white">
                Something short and leading about the collection below—its
                contents, the creator, etc. Make it short and sweet, but not too
                short so folks don’t simply skip over it entirely.
              </p>
            </div>
          </div>
        </section>

        <div className="album py-5 my-5">
          <div className="container">
            <div
              className="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3"
              data-aos="fade-up"
              data-aos-anchor-placement="top-center"
            >
              {videoIDs &&
                videoIDs.map((data) => <VideoCard embedId={data.id} />)}
            </div>
          </div>
        </div>

        <Featurettes />

        {/* <section className="container py-5">
          <div className="row">
            <div className="col-10 mx-auto">
              <VideoCard embedId="5EfMInocDs8" />{" "}
            </div>
          </div>
        </section> */}
        <CallToAction />
        <FAQ />
        <Subscribe />
      </main>
    </div>
  );
}
