import Hero from "../components/Hero/Hero";
import Head from "next/head";
const presets = () => {
  return (
    <>
      <Hero>
        <Head>
          <title>Mekoyo Production</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className="container">
          <div className="py-5 my-5">
            <h1>Sample and Presets</h1>
            <button className="btn btn-primary rounded-0 btn-lg ">
              See More
            </button>
          </div>
        </header>
      </Hero>
    </>
  );
};

export default presets;
