import React from "react";
import VideoCard from "../components/Cards/VideoCard";
import Hero from "../components/Hero/Hero";
import Head from "next/head";
const tutorials = () => {
  const videoIDs = [
    { id: "1kx0FfSexQ0" },
    { id: "5EfMInocDs8" },
    { id: "X3DDFB0BiQw" },
    { id: "Y6AKl_8XKJQ" },
  ];
  return (
    <>
      <Head>
        <title>Mekoyo Production</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <header className="container">
          <hgroup>
            <h1>Tutorial Videos</h1>
            <h2>A Catalogue of Youtube Video Tutorials</h2>
          </hgroup>
        </header>
      </Hero>
      <div className="container ">
        <div className="row row-cols-1 row-cols-sm-2 row-cols-md-3 py-5 g-3">
          {videoIDs &&
            videoIDs.map((data, index) => (
              <VideoCard key={index} embedId={data.id} />
            ))}
        </div>
      </div>
    </>
  );
};

export default tutorials;
